### ISSUE TITLE
Confusing display of added effects in UI

### ISSUE THREAD

**Issue by mboeringa** [annelfitz/cim-symbol-builder-js#2]
The current display of the added effects is confusing. In the image below, it suggests that I have already added three effects, while in reality, only the first two have been committed, and the third is just a box to choose a new one. This is not so intuitive...

![afbeelding](https://user-images.githubusercontent.com/7635726/134563842-492bb71e-e395-4a7c-a929-685f43461da3.png)

**Comment by annelfitz** [comment]
@mboeringa - thanks for all of your great feedback! I'll get to work on these issues shortly.

**Comment by annelfitz** [comment]
@mboeringa - This is installed. Hopefully this UI works better for you! Let me know if you have any feedback.
