### ISSUE TITLE
Allow deleting effect like layer

### ISSUE THREAD

**Issue by mboeringa** [annelfitz/cim-symbol-builder-js#3]
Currently, to delete an effect, you need to open up the properties of the effect, while for symbol layers, you can simply hit the button next to it, which is more intuitive and direct:

![afbeelding](https://user-images.githubusercontent.com/7635726/134564398-a38154f0-44eb-43e6-b4be-f28e09c0ff7c.png)

**Comment by annelfitz** [comment]
@mboeringa - This is installed. Thanks again for the feedback!

**Comment by mboeringa** [comment]
@annelfitz 

Good to hear that, will give it a try.

Marco
