### ISSUE TITLE
Width settings < 1 for hatch lines appear not to be propery visually applied

### ISSUE THREAD

**Issue by mboeringa** [annelfitz/cim-symbol-builder-js#4]
See attached image. Note that setting the **outline** width of the symbol to a value less than 1, does seem to properly work, it is only the hatch lines' widths that fail to be properly set / displayed when a setting < 1 is used (e.g. 0.2). Instead of seeing the width clearly being diminished, the lines stay the same width as line width 1, but are rendered in a lighter grey color, the narrower you make the line going from 1 to e.g. 0.1.

![afbeelding](https://user-images.githubusercontent.com/7635726/136097490-57433efb-5d62-44b8-aae3-940f780e75ff.png)

**Comment by annelfitz** [comment]
@mboeringa - thanks for pointing this out! Seems to be a bug in the API. We'll look into it.

**Comment by mboeringa** [comment]
Yes, please do. Being limited to 1pt line widths minimum is pretty limiting to the cartographic options.

**Comment by annelfitz** [comment]
Hi @mboeringa - this issue will be fixed with our November release in a couple weeks. Thank you for your patience!

**Comment by annelfitz** [comment]
A fix has been installed with today's update of the CIMSymbolBuilder. Thanks again for reporting this.
